spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user-service
            - name: CircuitBreaker
              args:
                name: patientServiceCB
                fallbackUri: forward:/fallback/patient-service
            - name: CircuitBreaker
              args:
                name: doctorServiceCB
                fallbackUri: forward:/fallback/doctor-service
            - name: CircuitBreaker
              args:
                name: appointmentServiceCB
                fallbackUri: forward:/fallback/appointment-service
            - name: CircuitBreaker
              args:
                name: medicalRecordServiceCB
                fallbackUri: forward:/fallback/medical-record-service
            - name: CircuitBreaker
              args:
                name: consultationServiceCB
                fallbackUri: forward:/fallback/consultation-service
            - name: CircuitBreaker
              args:
                name: pharmacyServiceCB
                fallbackUri: forward:/fallback/pharmacy-service
            - name: CircuitBreaker
              args:
                name: insuranceClaimServiceCB
                fallbackUri: forward:/fallback/insurance-service

        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/v1/patient/**

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/v1/doctor/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/**

        - id: medical-record-service
          uri: lb://medical-record-service
          predicates:
            - Path=/api/v1/medical/**

        - id: consultation-service
          uri: lb://consultation-service
          predicates:
            - Path=/api/v1/consultation/**

        - id: pharmacy-service
          uri: lb://pharmacy-service
          predicates:
            - Path=/api/v1/pharmacy/**

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/v1/billing/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**

        - id: insurance-claim-service
          uri: lb://insurance-claim-service
          predicates:
            - Path=/api/v1/insurance/**
resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      patientServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      doctorServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      appointmentServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      medicalRecordServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      consultationServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      pharmacyServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      billingServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      notificationServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      insuranceClaimServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10