spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8088
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user-service

        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/v1/patient/**
          filters:
            - name: CircuitBreaker
              args:
                name: patientServiceCB
                fallbackUri: forward:/fallback/patient-service

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/v1/doctor/**
          filters:
            - name: CircuitBreaker
              args:
                name: doctorServiceCB
                fallbackUri: forward:/fallback/doctor-service

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointmentServiceCB
                fallbackUri: forward:/fallback/appointment-service

        - id: medical-record-service
          uri: lb://medical-record-service
          predicates:
            - Path=/api/v1/medical/**
          filters:
            - name: CircuitBreaker
              args:
                name: medicalRecordServiceCB
                fallbackUri: forward:/fallback/medical-service

        - id: consultation-service
          uri: lb://consultation-service
          predicates:
            - Path=/api/v1/consultation/**
          filters:
            - name: CircuitBreaker
              args:
                name: consultationServiceCB
                fallbackUri: forward:/fallback/consultation-service

        - id: pharmacy-service
          uri: lb://pharmacy-service
          predicates:
            - Path=/api/v1/pharmacy/**
          filters:
            - name: CircuitBreaker
              args:
                name: pharmacyServiceCB
                fallbackUri: forward:/fallback/pharmacy-service

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/v1/billing/**
          filters:
            - name: CircuitBreaker
              args:
                name: billingServiceCB
                fallbackUri: forward:/fallback/billing-service

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCB
                fallbackUri: forward:/fallback/notification-service

        - id: insurance-claim-service
          uri: lb://insurance-claim-service
          predicates:
            - Path=/api/v1/insurance/**
          filters:
            - name: CircuitBreaker
              args:
                name: insuranceClaimServiceCB
                fallbackUri: forward:/fallback/insurance-service
resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      patientServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      doctorServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      appointmentServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      medicalRecordServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      consultationServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      pharmacyServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      billingServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      notificationServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
      insuranceClaimServiceCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true